refactor: update deploy-carat-dev-stg.yml

diff --git a/.github/workflows/deploy-carat-dev-stg.yml b/.github/workflows/deploy-carat-dev-stg.yml
--- a/.github/workflows/deploy-carat-dev-stg.yml
+++ b/.github/workflows/deploy-carat-dev-stg.yml
@@ -33,6 +33,13 @@ jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
+      - name: Check for SHA and Tag
+        run: |
+          if [ -z "${{ github.event.inputs.DOCKER_IMAGE_SHA }}" ] && [ -z "${{ github.event.inputs.DOCKER_IMAGE_TAG }}" ]; then
+            echo "Error: Both SHA and Tag are empty. Exiting."
+            exit 1
+          fi
+          
       - name: Install Docker
         run: |
           sudo apt-get update
@@ -54,12 +61,6 @@ jobs:
         run: |
           echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
 
-      - name: Check for SHA and Tag
-        run: |
-          if [ -z "${{ github.event.inputs.DOCKER_IMAGE_SHA }}" ] && [ -z "${{ github.event.inputs.DOCKER_IMAGE_TAG }}" ]; then
-            echo "Error: Both SHA and Tag are empty. Exiting."
-            exit 1
-          fi
 
       - name: Verify Docker image using tag and retrieve SHA digest
         if: ${{ github.event.inputs.DOCKER_IMAGE_SHA == '' }}
