try again

diff --git a/.github/workflows/deploy-carat-dev-stg.yml b/.github/workflows/deploy-carat-dev-stg.yml
--- a/.github/workflows/deploy-carat-dev-stg.yml
+++ b/.github/workflows/deploy-carat-dev-stg.yml
@@ -54,12 +54,28 @@ jobs:
         run: |
           echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
 
+      - name: Verify Docker image using SHA and trap "Pulling from ..."
+        if: ${{ github.event.inputs.DOCKER_IMAGE_SHA != '' }}
+        run: |
+          REPO="altonium/${{ github.event.inputs.DEPLOY_APP }}-${{ github.event.inputs.DEPLOY_ENV }}"
+          SHA="${{ github.event.inputs.DOCKER_IMAGE_SHA }}"
+          echo "Pulling Docker image with SHA: $SHA"
+          OUTPUT=$(docker pull --platform linux/amd64 $REPO@$SHA 2>&1)
+          if echo "$OUTPUT" | grep -q "Pulling from"; then
+            echo "Docker image with SHA $SHA is being pulled."
+            echo "IMAGE_REF=$SHA" >> $GITHUB_ENV
+          else
+            echo "Error: Docker image with SHA $SHA not found."
+            exit 1
+          fi
+
+
       - name: Install kubectl
         run: |
           curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
           chmod +x ./kubectl
           sudo mv ./kubectl /usr/local/bin/kubectl
-
+  
       - name: Install Helm
         run: |
           curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
@@ -69,39 +85,7 @@ jobs:
           mkdir -p $HOME/.kube  # Create the .kube directory if it doesn't exist
           echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 --decode > $HOME/.kube/config
           chmod 600 $HOME/.kube/config
-
-      - name: Verify Docker image using SHA and trap "Pulling from ..."
-        if: ${{ github.event.inputs.DOCKER_IMAGE_SHA != '' }}
-        run: |
-          REPO="altonium/${{ github.event.inputs.DEPLOY_APP }}-${{ github.event.inputs.DEPLOY_ENV }}"
-          SHA="${{ github.event.inputs.DOCKER_IMAGE_SHA }}"
-          echo "Pulling Docker image with SHA: $SHA"
-          OUTPUT=$(docker pull --platform linux/amd64 $REPO@$SHA 2>&1 | tee /dev/tty)
-          if echo "$OUTPUT" | grep -q "Pulling from"; then
-            echo "Docker image with SHA $SHA is being pulled."
-            echo "IMAGE_REF=$SHA" >> $GITHUB_ENV
-            kill $! 2>/dev/null || true  # Safely attempt to cancel the pull
-          else
-            echo "Error: Docker image with SHA $SHA not found."
-            exit 1
-          fi
-
-      - name: Verify Docker image using tag and trap "Pulling from ..."
-        if: ${{ github.event.inputs.DOCKER_IMAGE_SHA == '' }}
-        run: |
-          REPO="altonium/${{ github.event.inputs.DEPLOY_APP }}-${{ github.event.inputs.DEPLOY_ENV }}"
-          TAG="${{ github.event.inputs.DOCKER_IMAGE_TAG }}"
-          echo "Pulling Docker image with tag: $TAG"
-          OUTPUT=$(docker pull --platform linux/amd64 $REPO:$TAG 2>&1 | tee /dev/tty)
-          if echo "$OUTPUT" | grep -q "Pulling from"; then
-            DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $REPO:$TAG | sed 's/.*@//')
-            echo "Docker image with tag $TAG is being pulled."
-            echo "IMAGE_REF=$DIGEST" >> $GITHUB_ENV
-            kill $! 2>/dev/null || true  # Safely attempt to cancel the pull
-          else
-            echo "Error: Docker image with tag $TAG not found."
-            exit 1
-          fi
+  
 
       - name: Checkout repository
         uses: actions/checkout@v4
